//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_Entity_Framework.DataConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SinavOgrenciEntities : DbContext
    {
        public DB_SinavOgrenciEntities()
            : base("name=DB_SinavOgrenciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_dersler> tbl_dersler { get; set; }
        public virtual DbSet<tbl_notlar> tbl_notlar { get; set; }
        public virtual DbSet<tbl_ogrenci> tbl_ogrenci { get; set; }
        public virtual DbSet<tbl_kulupler> tbl_kulupler { get; set; }
    
        public virtual ObjectResult<NOTLISTESI_Result> NOTLISTESI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NOTLISTESI_Result>("NOTLISTESI");
        }
    }
}
